sudo: required
services:
  - docker

before_install:
  - docker build -t shambho/shambhov1 -f Dockerfile.dev .

script:
  - docker run shambho/shambhov1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  name: shambhov1
  env: "Shambhov1-env"
  bucket_name: "elasticbeanstalk-us-east-1-367318235946"
  bucket_path: "shambhov1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"